lab 1 Chanova K33422
TonikX/ITMO_ICT_WebDevelopment_2020-2021 pull request #14
Opened 2020-09-23 20:00 UTC by spiritofsofya

2020-10-02 07:55 UTC, TonikX requested changes
Необходимо доработать http заголовок в 3 задании.

2020-10-02 08:35 UTC, spiritofsofya commented
![image](https://user-images.githubusercontent.com/43500571/94904011-16ea2480-04b4-11eb-9c45-c3a3f0c83de5.png)
Теперь сообщение клиенту отображается в браузере.

2020-10-28 10:27 UTC, TonikX commented
ЛР1 - Зачтено.

2020-10-30 10:08 UTC, TonikX approved these changes
Зачтено.

2020-10-30 10:08 UTC, merged