Дубина Сергей К33402 - 1 лаба
TonikX/ITMO_ICT_WebDevelopment_2020-2021 pull request #26
Opened 2020-09-25 19:39 UTC by spinaBelaya

2020-09-30 16:35 UTC, TonikX submitted a review, later dismissed

2020-09-30 16:35 UTC, TonikX commented on students/K33402/Dubina Sergey/lab1/3/serv_html.py
> +header = bytes(f'HTTP/1.0 200 OK\nContent-Type: text/html\n\n{message}', 'utf-8')
Необходимо исправить заговловки.

2020-12-23 16:53 UTC, kantegory requested changes
Не нашёл основного кода по работе. Просьба его предоставить. Из того, что тут есть вижу только миграции, admin.py, apps.py. Нужно дозагрузить всё остальное.

2020-12-23 18:09 UTC, kantegory approved these changes

2020-12-23 18:13 UTC, kantegory commented
Принимаю. Если докините в документацию примеры запросов и ответов (подразумеваю json), то баллы повысятся. Отправлять в новом PR.

2020-12-23 18:13 UTC, merged